# Generated by Django 2.2.3 on 2019-07-24 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockedWords',
            new_name='BlockedWord',
        ),
        migrations.RenameField(
            model_name='blockedword',
            old_name='users',
            new_name='user',
        ),
    ]
