# Generated by Django 2.2.3 on 2019-07-24 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_analysis', '0004_auto_20190724_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blockedword',
            old_name='user',
            new_name='users',
        ),
    ]
